#!/usr/bin/env sh

VERBOSITY=8
PASSPHRASE=$(gpg2 --decrypt --quiet $HOME/.duplicity/google.gpg)
EXCLUDE_IF_PRESENT=".noback"
EXCLUDE_FILELIST=$HOME/.duplicity/excludes
OFFSITE_DEST="gdocs://pagansoft@gmail.com/duplicity"
OFFSITE_EXCLUDE_FILELIST=$EXCLUDE_FILELIST
OFFSITE_EXCLUDE_IF_PRESENT=$EXCLUDE_IF_PRESENT
OFFSITE_FULL_EVERY="90D"
OFFSITE_KEEP_FULL=1
export GOOGLE_DRIVE_SETTINGS=$HOME/.duplicity/credentials

cd $HOME/.duplicity

duplicity --verbosity=0 cleanup --force ${OFFSITE_DEST}
if [ $VERBOSITY -gt 0 ]; then
  echo "Performing an offsite backup to ${OFFSITE_DEST}"
fi

duplicity \
  --verbosity=$VERBOSITY \
  --allow-source-mismatch \
  --full-if-older-than=$OFFSITE_FULL_EVERY \
  --exclude-if-present=$OFFSITE_EXCLUDE_IF_PRESENT \
  --exclude-filelist=$OFFSITE_EXCLUDE_FILELIST \
  $HOME ${OFFSITE_DEST}

if [ $VERBOSITY -gt 0 ]; then
  echo "Removing all but ${OFFSITE_KEEP_FULL} full backups from ${OFFSITE_DEST}"
fi

duplicity \
  --verbosity=$VERBOSITY \
  remove-all-but-n-full ${OFFSITE_KEEP_FULL} \
  --force ${OFFSITE_DEST}
