#!/usr/bin/env bash

set -e

BASE_CONFIG="base"
CONFIG_SUFFIX=".json"

META_DIR="meta"
CONFIG_DIR="configs"
PROFILES_DIR="profiles"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


cd "${BASE_DIR}"
git -C "${META_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${META_DIR}"


while IFS= read -r config; do
    CONFIGS+=" ${config}"
done < "${META_DIR}/${PROFILES_DIR}/$1"

shift


"${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" --plugin-dir "${META_DIR}/dotbot-brewfile" -p "${META_DIR}/dotbot-aptget-sudo/aptget.py" -c "${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}"

for config in ${CONFIGS} ${@}; do
    echo -e "\nConfigure $config"
    "${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" --plugin-dir "${META_DIR}/dotbot-brewfile" -p "${META_DIR}/dotbot-aptget-sudo/aptget.py" -c "${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}"
done
