#!/usr/bin/env bash

set -e

BASE_CONFIG="base"
CONFIG_SUFFIX=".json"

META_DIR="meta"
CONFIG_DIR="configs"
PROFILES_DIR="profiles"

PLUGIN_BREW=--plugin-dir "${META_DIR}/dotbot-brewfile"
PLUGIN_APT=--plugin-dir "${META_DIR}/dotbot_plugin_aptget"
PLUGINS=${PLUGIN_BREW} ${PLUGIN_APT}

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"


cd "${BASE_DIR}"
git submodule update --init --recursive --remote


"${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" ${PLUGINS} -c "${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}"

for config in ${@}; do
    "${BASE_DIR}/${META_DIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASE_DIR}" ${PLUGINS} -c "${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}"
done
