#!/bin/env sh

$HOME/bin/1punlock >/dev/null 2>/dev/null

if [ $? = 0 ]; then
  $HOME/bin/1pc -act list | sort | uniq
  exit $?
fi
  
notify-send -u critical -a "1Password" "Could not open vault!"
exit $result
