#!/bin/env sh

items=$($HOME/bin/1plist)
if [ $? = 0 ]; then
 vaultname=$(cat ~/.config/onepaq/current)
 item=$(echo -e "$items" | rofi -matching fuzzy -dmenu -i -p "$vaultname")
  if [ $? = 0 ]; then
    password=$($HOME/bin/1pread "$item")
    if [ $? = 0 ]; then
      notify-send -u low "Password for \"$item\" copied to clipboard"
      echo $password | xclip
      exit 0
    fi
  fi
fi
