#!/bin/env sh

items=$($HOME/bin/1plist)
if [ $? = 0 ]; then
  item=$(echo -e "$items" | rofi -matching fuzzy -dmenu -p "Select Password")
  if [ $? = 0 ]; then
    password=$($HOME/bin/1pread "$item")
    if [ $? = 0 ]; then
      notify-send -u low "Password for \"$item\" copied to clipboard"
      echo $password | xclip
      exit 0
    fi
  fi
fi
