#!/bin/env sh

$HOME/bin/1punlock >/dev/null 2>/dev/null

if [ $? = 0 ]; then
  $HOME/bin/1pc -act read -item "$1"
  exit $?
fi

vaultname=$(cat ~/.config/onepaq/current)
notify-send -u critical "Could not unlock vault $vaultname!"
exit 1
