#!/bin/env sh

CONF=~/.config/onepaq
current=$(cat $CONF/current)

new=$(ls $CONF/profiles | rofi -dmenu -matching fuzzy -i -p "Select profile")

if [ "$new" != "" ]; then
  if [ "$current" != "$new" ]; then
    pkill onepaq
    while pgrep onepaq >/dev/null; do sleep 1; done
    rm $CONF/current.opvault
    ln -s $CONF/profiles/$new $CONF/current.opvault
    echo $new > $CONF/current
    ~/bin/1pmenu
    exit $?
  fi
fi
