#!/bin/env sh

pgrep onepaq >/dev/null 2>/dev/null || $HOME/bin/1pserver &

$HOME/bin/1pstatus >/dev/null 2>/dev/null
if [ $? = 0 ]; then
  exit 0
fi

vaultname=$(cat ~/.config/onepaq/current)
password=$(rofi -dmenu -l 0 -p "Password for $vaultname" -password 2>/dev/null)
if [ "$password" = "" ]; then
  notify-send -u critical "No password!"
  exit 1
fi

$HOME/bin/1pc -act unlock -pass $password
exit $?
