# qutebrowser shortcuts
config.bind(';dd', 'set downloads.location.directory ~/Dokumente ;; hint links download')
config.bind(';df', 'set downloads.location.directory ~/.dotfiles ;; hint links download')
config.bind(';dr', 'set downloads.location.directory ~/Dropbox ;; hint links download')
config.bind(';dl', 'set downloads.location.directory ~/Downloads ;; hint links download')
config.bind(';D', 'set downloads.location.directory ~/Downloads ;; hint links download')
config.bind(';m', 'set downloads.location.directory ~/Musik ;; hint links download')
config.bind(';pp', 'set downloads.location.directory ~/Bilder ;; hint links download')
config.bind(';vv', 'set downloads.location.directory ~/Videos ;; hint links download')
config.bind(';s', 'set downloads.location.directory ~/.dotfiles/scripts ;; hint links download')
config.bind(';cf', 'set downloads.location.directory ~/.config ;; hint links download')
