#!/bin/sh

path_ac="/sys/class/power_supply/AC"
path_battery_0="/sys/class/power_supply/BAT0"
path_battery_1="/sys/class/power_supply/BAT1"

ac=0
battery_level_0=0
battery_level_1=0
battery_max_0=0
battery_max_1=0

if [ -f "$path_ac/online" ]; then
  ac=$(cat "$path_ac/online")
fi

if [ -f "$path_battery_0/energy_now" ]; then
  battery_level_0=$(cat "$path_battery_0/energy_now")
fi

if [ -f "$path_battery_0/energy_full" ]; then
  battery_max_0=$(cat "$path_battery_0/energy_full")
fi

if [ -f "$path_battery_1/energy_now" ]; then
  battery_level_1=$(cat "$path_battery_1/energy_now")
fi

if [ -f "$path_battery_1/energy_full" ]; then
  battery_max_1=$(cat "$path_battery_1/energy_full")
fi

battery_level=$(("$battery_level_0 + $battery_level_1"))
battery_max=$(("$battery_max_0 + $battery_max_1"))

battery_percent=$(("$battery_level * 100"))
battery_percent=$(("$battery_percent / $battery_max"))

text="$battery_percent % "

color="#d8dee9"
if [ "$ac" -eq 1 ]; then
  icon=""
  if [ "$battery_percent" -gt 88 ]; then
    icon=""
    text=""
  fi
else

  if [ "$battery_percent" -gt 95 ]; then
    icon=""
  elif [ "$battery_percent" -gt 88 ]; then
    icon=""
  elif [ "$battery_percent" -gt 79 ]; then
    icon=""
  elif [ "$battery_percent" -gt 69 ]; then
    icon=""
  elif [ "$battery_percent" -gt 59 ]; then
    icon=""
  elif [ "$battery_percent" -gt 49 ]; then
    icon=""
  elif [ "$battery_percent" -gt 39 ]; then
    icon=""
    color="#D65D0E"
  elif [ "$battery_percent" -gt 29 ]; then
    icon=""
    color="#D65D0E"
  elif [ "$battery_percent" -gt 19 ]; then
    icon=""
    color="#D65D0E"
  elif [ "$battery_percent" -gt 9 ]; then
    icon=""
    color="#CC241D"
  else
    icon=""
    color="#CC241D"
  fi
fi

echo "<fc=$color>$icon $text</fc>"
