#!/bin/bash

CMD=~/.cargo/bin/sonic-pi-tool
STATUS="$CMD check"

if ~/.cargo/bin/sonic-pi-tool check >/dev/null; then
  echo "<fn=2><action=/home/mgondermann/bin/toggle_pi>▶️</action></fn>"
else
  echo "<fn=2><action=/home/mgondermann/bin/toggle_pi>⏹️</action></fn>"
fi

