#!/bin/sh

options="Lock\nLogout\nSuspend\nHibernate\nReboot\nShutdown"

chosen=$(echo -e "$options" | /usr/bin/dmenu -fn "Monoid NF:16" -nb "#282828" -nf "#ebdbb2" -sb "#d65d0e" -sf "#ebdbb2" -i -l 10 -p "Bitte auswählen:")

lock() {
  /usr/bin/betterlockscreen -l dimblur &
}

case "$chosen" in
  Lock) lock ;;
  Logout) i3-msg exit ;;
  Suspend) systemctl suspend ;; 
  Hibernate) systemctl hibernate ;;
  Reboot) systemctl reboot ;;
  Shutdown) systemctl poweroff ;;
esac

exit 0
