#!/usr/bin/env sh
USER=$(who | cut -d' ' -f1)

if [[ -d ~/.oh-my-zsh ]]; then
  echo "Oh My Zsh is already installed"
else
  RUN_ZSH=no
  CHSH=no
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

if (cat /etc/passwd | grep $USER | grep /usr/bin/zsh); then
  echo "ZSH is already the default shell"
else
  chsh -s /usr/bin/zsh
fi
