#!/bin/sh

options="Lock\nLogout\nSuspend\nHibernate\nReboot\nShutdown"

chosen=$(echo -e "$options" | /usr/bin/rofi -i -l 6 -p "" -mesg "Option zum Beenden auswählen:" -dmenu)

lock() {
  /usr/bin/betterlockscreen -l dimblur &
}

case "$chosen" in
  Lock) lock ;;
  Logout) dwmc quit ;;
  Suspend) systemctl hybrid-sleep ;;
  Hibernate) systemctl hibernate ;;
  Reboot) systemctl reboot ;;
  Shutdown) systemctl poweroff ;;
esac

exit 0
