#!/bin/bash

CMD=/usr/bin/jack_control
STATUS="$CMD status"
STOP="$CMD stop"

RUNNING=$($STATUS > /dev/null 2>&1 && echo 1 || echo 0)

case $BLOCK_BUTTON in
  1) 
    if [[ $RUNNING -eq 0 ]]; then
     ~/bin/startjack > /dev/null 2>&1
    else
     ~/bin/stopjack > /dev/null 2>&1
    fi
    ;;
  3)
    /usr/bin/cadence & disown ;;
esac

RUNNING=$($STATUS > /dev/null 2>&1 && echo 1 || echo 0)

if [[ $RUNNING -eq 1 ]]; then
  echo " 🎤<span color=\"#689d6a\"> 栗</span>"
else
  echo " 🎤<span color=\"#cc241d\"> 契</span>"
fi

