#!/bin/bash

CMD=/usr/bin/jack_control
STATUS="$CMD status"
START="$CMD start"
STOP="$CMD stop"

RUNNING=$($STATUS > /dev/null 2>&1 && echo 1 || echo 0)

case $BLOCK_BUTTON in
  1) 
    if [[ $RUNNING -eq 0 ]]; then
     $START > /dev/null 2>&1
    else
     $STOP > /dev/null 2>&1
    fi
    ;;
  3)
    /usr/bin/cadence & disown ;;
esac

RUNNING=$($STATUS > /dev/null 2>&1 && echo 1 || echo 0)

if [[ $RUNNING -eq 1 ]]; then
  echo "<span color=\"green\">栗</span>"
else
  echo "<span color=\"red\">契</span>"
fi

