#!/bin/sh
case $BLOCK_BUTTON in
  1) /usr/bin/qutebrowser https://mail.google.com ;;
  3) /usr/bin/termite -e neomutt ;;
esac

COUNT=$(find ~/.mail -wholename */Posteingang/new/* | sed -n '$=') 

if [[ $COUNT -gt 0 ]]; then
  echo "<span color=\"#b8bb26\">$COUNT</span>" $(cat ~/.config/mutt/.dl 2>/dev/null)
else
 echo $(cat ~/.config/mutt/.dl 2>/dev/null)
fi
