#!/bin/bash

CMD=~/.cargo/bin/sonic-pi-tool
STATUS="$CMD check"
START="$CMD start-server"
STOP="pkill -9 -f /opt/sonic-pi"

RUNNING=$($STATUS > /dev/null 2>&1 && echo 1 || echo 0)

case $BLOCK_BUTTON in
  1)
    toggle_pi
    ;;
esac

RUNNING=$($STATUS > /dev/null 2>&1 && echo 1 || echo 0)

if [[ $RUNNING -eq 1 ]]; then
  echo " π <span color=\"#689d6a\">栗 </span>"
else
  echo " π <span color=\"#cc241d\">契 </span>"
fi

