#!/bin/bash

CMD=~/.cargo/bin/sonic-pi-tool
STATUS="$CMD check"
START="$CMD start-server"
STOP="pkill -9 -f /opt/sonic-pi"

RUNNING=$($STATUS > /dev/null 2>&1 && echo 1 || echo 0)

case $BLOCK_BUTTON in
  1) 
    if [[ $RUNNING -eq 0 ]]; then
     $START > /dev/null 2>&1 & disown
     sleep 1
    else
     $STOP > /dev/null 2>&1
     pkill -9 scsynth > /dev/null 2>&1
    fi
    ;;
esac

RUNNING=$($STATUS > /dev/null 2>&1 && echo 1 || echo 0)

if [[ $RUNNING -eq 1 ]]; then
  echo " π <span color=\"#689d6a\">栗 </span>"
else
  echo " π <span color=\"#cc241d\">契 </span>"
fi

