#!/usr/bin/env sh

function toggle() {
  amixer -c 0 set Master toggle >/dev/null 2>&1
}

case $BLOCK_BUTTON in
	1) /usr/bin/urxvt -e 'alsamixer -c 0' & disown ;;
	3) toggle;;
	4) amixer -c 0 sset Master 1%+ >/dev/null 2>&1;;
	5) amixer -c 0 sset Master 1%- >/dev/null 2>&1;;
esac

V=$(amixer -M -c 0 sget Master | grep 'Mono:')
if [[ $(echo $V | sed -e 's/.*\[\(on\|off\)\].*/\1/g') = "off" ]]; then
  echo "🔇 <span color=\"#98971A\">[mute]</span>"
else
  VOLUME=$(echo $V | sed -e 's/.*\[\([[:digit:]]\+\)%\].*/\1/gm')
  if [[ ${VOLUME} -gt 75 ]]; then
    echo " 🔊 $VOLUME% "
  elif [[ ${VOLUME} -gt 25 ]]; then
    echo " 🔉 $VOLUME% "
  else
    echo " 🔈 $VOLUME% "
  fi
fi
