#!/bin/bash

# Feed script a url.
# If an image, it will view in feh,
# if a video or gif, it will view in mpv
# if a music file or pdf, it will download,
# otherwise it opens link in browser.

[ -z "$1-" ] && { "$TRUEBROWSER"; exit; }

case "${1}" in
  *mkv|*webm|*mp4|*gif|*youtube.com*)
    setsid mpv -quiet "${1}" >/dev/null 2>&1 & ;;
  *png|*jpg|*jpe|*jpeg)
    setsid feh "${1}" >/dev/null 2>&1 & ;;
  *mp3|*flac|*opus|*mp3?source)
    setsid tsp wget "${1}" >/dev/null 2>&1 & ;;
  *) setsid "${TRUEBROWSER}" "${1}" >/dev/null 2>&1 & ;;
esac

