#!/bin/bash

/usr/bin/mpc stop

/usr/bin/jack_control stop
sleep 1
/usr/bin/jack_control eps realtime true
/usr/bin/jack_control ds alsa
/usr/bin/jack_control dps device hw:CODEC
/usr/bin/jack_control dps capture hw:CODEC
/usr/bin/jack_control dps playback hw:CODEC
/usr/bin/jack_control dps nperiods 3
/usr/bin/jack_control dps period 128
/usr/bin/jack_control dps rate 48000
/usr/bin/jack_control start

if pgrep dwmblocks; then
  pkill -RTMIN+9 dwmblocks
else
  pkill -RTMIN+9 i3blocks
fi
