#!/bin/bash

case "$1" in
  "up") amixer -c 0 sset Master 5%+ && pkill -RTMIN+10 i3blocks ;;
  "fineup") amixer -c 0 sset Master 1%+ && pkill -RTMIN+10 i3blocks ;;
  "down") amixer -c 0 sset Master 5%- && pkill -RTMIN+10 i3blocks ;;
  "finedown") amixer -c 0 sset Master 1%- && pkill -RTMIN+10 i3blocks ;;
  "mute") pamixer --allow-boost -t && pkill -RTMIN+10 i3blocks ;;
  "truemute") pamixer --allow-boost -m && pkill -RTMIN+10 i3block s;;
  "toggle") mpc toggle && pkill -RTMIN+11 i3blocks ;;
  "stop") mpc stop && pkill -RTMIN+11 i3blocks ;;
  "pause") mpc pause && pkill -RTMIN+10 i3blocks ;;
  "forward") mpc seek +"$2" && pkill -RTMIN+11 i3blocks ;;
  "back") mpc seek -"$2" && pkill -RTMIN+11 i3blocks ;;
  "next") mpc next && pkill -RTMIN+11 i3blocks ;;
  "prev") mpc prev && pkill -RTMIN+11 i3blocks ;;
  "replay") mpc seek 0% && pkill -RTMIN+11 i3blocks ;;
esac

exit
