#!/bin/bash

case "$1" in
  "up") pamixer --allow-boost -i "$2" ;;
  "down") pamixer --allow-boost -d "$2" ;;
  "mute") pamixer --allow-boost -t ;;
  "truemute") pamixer --allow-boost -m ;;
  "toggle") mpc toggle && pkill -RTMIN+11 i3blocks ;;
  "pause") mpc pause && pkill -RTMIN+11 i3blocks ;;
  "forward") mpc seek +"$2" && pkill -RTMIN+11 i3blocks ;;
  "back") mpc seek -"$2" && pkill -RTMIN+11 i3blocks ;;
  "next") mpc next && pkill -RTMIN+11 i3blocks ;;
  "prev") mpc prev && pkill -RTMIN+11 i3blocks ;;
  "replay") mpc seek 0% && pkill -RTMIN+11 i3blocks ;;
esac

exit
