#!/bin/bash

DEVICE=${1-hw:PCH}
PERIOD=${2-512}

/usr/bin/mpc stop

/usr/bin/jack_control stop
sleep 1
/usr/bin/jack_control eps realtime true
/usr/bin/jack_control ds alsa
/usr/bin/jack_control dps device ${DEVICE}
/usr/bin/jack_control dps capture ${DEVICE}
/usr/bin/jack_control dps playback ${DEVICE}
/usr/bin/jack_control dps nperiods 2
/usr/bin/jack_control dps period ${PERIOD}
/usr/bin/jack_control dps rate 48000
/usr/bin/jack_control start

pkill -RTMIN+9 i3blocks
