#!/bin/bash

if (lsusb | grep "Texas Instruments PCM2902 Audio Codec" >/dev/null); then
  DEVICE=${1-hw:CODEC}
  PERIOD=${2-128}
else
  DEVICE=${1-hw:PCH}
  PERIOD=${2-512}
fi

if [[ "${DEVICE}" == "usb" ]]; then
  DEVICE="hw:CODEC"
  PERIOD=128
fi

/usr/bin/mpc stop

/usr/bin/jack_control stop
sleep 1
/usr/bin/jack_control eps realtime true
/usr/bin/jack_control ds alsa
/usr/bin/jack_control dps device ${DEVICE}
/usr/bin/jack_control dps capture ${DEVICE}
/usr/bin/jack_control dps playback ${DEVICE}
/usr/bin/jack_control dps nperiods 2
/usr/bin/jack_control dps period ${PERIOD}
/usr/bin/jack_control dps rate 48000
/usr/bin/jack_control start

pkill -RTMIN+9 i3blocks
