#!/bin/bash
/usr/bin/jack_control stop
pkill -9 jackdbus

cd ${HOME}/.config/mpv
rm config
ln -s config.pulse config

if pgrep dwmblocks > /dev/null; then
  pkill -RTMIN+9 dwmblocks
else
  pkill -RTMIN+9 i3blocks
fi
