#!/usr/bin/env bash

if pgrep picom; then
  pkill picom
else
  if pgrep dwm > /dev/null; then
    picom -CG --experimental-backends & disown
  else
    if pgrep xmonad > /dev/null; then
      picom -CG --experimental-backends & disown
    else
      picom -cC --experimental-backends & disown
    fi
  fi
fi
