#!/bin/env sh

DISPLAY=:0
timeout=$(xset q | awk '/DPMS is/ {print $3}')
if [[ ${timeout} = "Disabled" ]]; then
  xset s on
  xset dpms 900 900 900
  xautolock -enable
  notify-send -u low -a "Screensaver" "Screensaver is now on"
else
  xset dpms 0 0 0
  xset -dpms
  xset s off
  xautolock -disable
  notify-send -u low -a "Screensaver" "Screensaver is now off"
fi
