#!/bin/env sh

DISPLAY=:0
timeout=$(xset q | awk '/DPMS is/ {print $3}')
if [[ ${timeout} = "Disabled" ]]; then
  start_screensaver
  notify-send -u low -a "Screensaver" "Screensaver is now on"
else
  stop_screensaver
  notify-send -u low -a "Screensaver" "Screensaver is now off"
fi
