#!/usr/bin/env bash

iDIR="$HOME/.config/mako/icons"

# Get brightness
get_backlight() {
	backlight="$(brightnessctl g)"
	max="$(brightnessctl m)"
	percent="$(echo "${backlight}*100/${backlight}" | bc)"
	echo "${percent}%"
}

# Get icons
get_icon() {
	backlight="$(brightnessctl g)"
	max="$(brightnessctl m)"
	percent="$(echo "${backlight}*100/${max}" | bc)"
	current="${percent%%%}"
	if [[ ("$current" -ge "0") && ("$current" -le "20") ]]; then
		icon="$iDIR/brightness-20.png"
	elif [[ ("$current" -ge "21") && ("$current" -le "40") ]]; then
		icon="$iDIR/brightness-40.png"
	elif [[ ("$current" -ge "41") && ("$current" -le "60") ]]; then
		icon="$iDIR/brightness-60.png"
	elif [[ ("$current" -ge "61") && ("$current" -le "80") ]]; then
		icon="$iDIR/brightness-80.png"
	elif [[ ("$current" -ge "81") && ("$current" -le "255") ]]; then
		icon="$iDIR/brightness-100.png"
	fi
}

# Notify
notify_user() {
	get_icon
	notify-send -h string:x-canonical-private-synchronous:sys-notify -c volume -u low -i "$icon" "Brightness : ${percent}%"
}

# Increase brightness
inc_backlight() {
	brightnessctl set 10%+ > /dev/null 2>&1  && notify_user
}

# Decrease brightness
dec_backlight() {
	brightnessctl set 10%- > /dev/null 2>&1 && notify_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_backlight
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
